{
    "url": "https://api.github.com/repos/spack/spack/issues/13532",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/13532/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/13532/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/13532/events",
    "html_url": "https://github.com/spack/spack/issues/13532",
    "id": 515969391,
    "node_id": "MDU6SXNzdWU1MTU5NjkzOTE=",
    "number": 13532,
    "title": "py-astor is not compatible with latest version of py-setuptools",
    "user": {
        "login": "Sinan81",
        "id": 2924561,
        "node_id": "MDQ6VXNlcjI5MjQ1NjE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2924561?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Sinan81",
        "html_url": "https://github.com/Sinan81",
        "followers_url": "https://api.github.com/users/Sinan81/followers",
        "following_url": "https://api.github.com/users/Sinan81/following{/other_user}",
        "gists_url": "https://api.github.com/users/Sinan81/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Sinan81/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Sinan81/subscriptions",
        "organizations_url": "https://api.github.com/users/Sinan81/orgs",
        "repos_url": "https://api.github.com/users/Sinan81/repos",
        "events_url": "https://api.github.com/users/Sinan81/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Sinan81/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 73908754,
            "node_id": "MDU6TGFiZWw3MzkwODc1NA==",
            "url": "https://api.github.com/repos/spack/spack/labels/bug",
            "name": "bug",
            "color": "fc2929",
            "default": true,
            "description": null
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2019-11-01T08:11:07Z",
    "updated_at": "2019-11-04T16:22:00Z",
    "closed_at": "2019-11-04T16:22:00Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "It seems py-astor is not compatible with latest (v41.4.0) py-setuptools, hence yielding build error. However, it builds just fine with earlier versions of py-setuptools.\r\n\r\n### Steps to reproduce the issue\r\n\r\n```console\r\n$ spack install py-astor\r\n...\r\n    specifiers = [s.strip() for s in specifiers.split(\",\") if s.strip()]\r\nAttributeError: 'SpecifierSet' object has no attribute 'split'\r\n==> Error: ProcessError: Command exited with status 1:\r\n    '/mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/python-2.7.16-xpjw43slye3gpenkpif4lzajlfpsj2b2/bin/python2.7' '\r\n-s' 'setup.py' '--no-user-cfg' 'build'\r\nSee build log for details:\r\n  /cache/sbulut/spack-stage/spack-stage-py-astor-0.8.0-4xsdi27ycyhhgeurnqui2f3e75yzjwqf/spack-build-out.txt\r\n```\r\n### Information on your system\r\n\r\n- Centos7\r\n- python@2.7.16",
    "performed_via_github_app": null
}