{
    "url": "https://api.github.com/repos/spack/spack/issues/1370",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/1370/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/1370/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/1370/events",
    "html_url": "https://github.com/spack/spack/issues/1370",
    "id": 167602929,
    "node_id": "MDU6SXNzdWUxNjc2MDI5Mjk=",
    "number": 1370,
    "title": "qa : issues with flake8 update and OrderedDict",
    "user": {
        "login": "alalazo",
        "id": 4199709,
        "node_id": "MDQ6VXNlcjQxOTk3MDk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4199709?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/alalazo",
        "html_url": "https://github.com/alalazo",
        "followers_url": "https://api.github.com/users/alalazo/followers",
        "following_url": "https://api.github.com/users/alalazo/following{/other_user}",
        "gists_url": "https://api.github.com/users/alalazo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/alalazo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/alalazo/subscriptions",
        "organizations_url": "https://api.github.com/users/alalazo/orgs",
        "repos_url": "https://api.github.com/users/alalazo/repos",
        "events_url": "https://api.github.com/users/alalazo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/alalazo/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 5,
    "created_at": "2016-07-26T13:09:42Z",
    "updated_at": "2016-07-31T03:25:19Z",
    "closed_at": "2016-07-31T03:25:19Z",
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "It seems the last update of `flake8` removed support for python 2.6  : \n\n```\nFile \"/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/utils.py\", line 287, in parameters_for\n    parameters = collections.OrderedDict([\nAttributeError: 'module' object has no attribute 'OrderedDict'\n```\n\nwhich makes all the tests failing since yesterday. What if we run flake8 checks only for python2.7 ?\n",
    "performed_via_github_app": null
}