{
    "url": "https://api.github.com/repos/spack/spack/issues/16263",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/16263/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/16263/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/16263/events",
    "html_url": "https://github.com/spack/spack/issues/16263",
    "id": 605753696,
    "node_id": "MDU6SXNzdWU2MDU3NTM2OTY=",
    "number": 16263,
    "title": "Question/issue: argument list too long",
    "user": {
        "login": "LDAmorim",
        "id": 15057096,
        "node_id": "MDQ6VXNlcjE1MDU3MDk2",
        "avatar_url": "https://avatars.githubusercontent.com/u/15057096?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/LDAmorim",
        "html_url": "https://github.com/LDAmorim",
        "followers_url": "https://api.github.com/users/LDAmorim/followers",
        "following_url": "https://api.github.com/users/LDAmorim/following{/other_user}",
        "gists_url": "https://api.github.com/users/LDAmorim/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/LDAmorim/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/LDAmorim/subscriptions",
        "organizations_url": "https://api.github.com/users/LDAmorim/orgs",
        "repos_url": "https://api.github.com/users/LDAmorim/repos",
        "events_url": "https://api.github.com/users/LDAmorim/events{/privacy}",
        "received_events_url": "https://api.github.com/users/LDAmorim/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 73908754,
            "node_id": "MDU6TGFiZWw3MzkwODc1NA==",
            "url": "https://api.github.com/repos/spack/spack/labels/bug",
            "name": "bug",
            "color": "fc2929",
            "default": true,
            "description": null
        },
        {
            "id": 1433532775,
            "node_id": "MDU6TGFiZWwxNDMzNTMyNzc1",
            "url": "https://api.github.com/repos/spack/spack/labels/triage",
            "name": "triage",
            "color": "ed9793",
            "default": false,
            "description": "The issue needs to be prioritized"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
        "login": "becker33",
        "id": 13971568,
        "node_id": "MDQ6VXNlcjEzOTcxNTY4",
        "avatar_url": "https://avatars.githubusercontent.com/u/13971568?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/becker33",
        "html_url": "https://github.com/becker33",
        "followers_url": "https://api.github.com/users/becker33/followers",
        "following_url": "https://api.github.com/users/becker33/following{/other_user}",
        "gists_url": "https://api.github.com/users/becker33/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/becker33/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/becker33/subscriptions",
        "organizations_url": "https://api.github.com/users/becker33/orgs",
        "repos_url": "https://api.github.com/users/becker33/repos",
        "events_url": "https://api.github.com/users/becker33/events{/privacy}",
        "received_events_url": "https://api.github.com/users/becker33/received_events",
        "type": "User",
        "site_admin": false
    },
    "assignees": [
        {
            "login": "becker33",
            "id": 13971568,
            "node_id": "MDQ6VXNlcjEzOTcxNTY4",
            "avatar_url": "https://avatars.githubusercontent.com/u/13971568?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/becker33",
            "html_url": "https://github.com/becker33",
            "followers_url": "https://api.github.com/users/becker33/followers",
            "following_url": "https://api.github.com/users/becker33/following{/other_user}",
            "gists_url": "https://api.github.com/users/becker33/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/becker33/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/becker33/subscriptions",
            "organizations_url": "https://api.github.com/users/becker33/orgs",
            "repos_url": "https://api.github.com/users/becker33/repos",
            "events_url": "https://api.github.com/users/becker33/events{/privacy}",
            "received_events_url": "https://api.github.com/users/becker33/received_events",
            "type": "User",
            "site_admin": false
        }
    ],
    "milestone": null,
    "comments": 4,
    "created_at": "2020-04-23T18:21:09Z",
    "updated_at": "2020-05-01T01:51:01Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "Hi all,\r\n\r\nI got into an issue using spack built packages that I installed without a problem (with ~blas~lapack due to openblas issue https://github.com/spack/spack/issues/16028).\r\nI don't know if it is a compatibility issue.\r\nBut I can't understand the issue.\r\nI saw similar things mentioned on other channels/websites and other spack issues, but I can't find something clearly related or that could fix it.\r\nSorry if this is a duplicate of another post.\r\n\r\nI am trying to run this script: \r\n[JN.txt](https://github.com/spack/spack/files/4524352/JN.txt)\r\n\r\nAnd I get the error: \r\n```\r\n$ bash JN.sh\r\n/Users/LDianaAmorim/Documents/opt/spack/share/spack/setup-env.sh: line 180: /Users/LDianaAmorim/Documents/opt/spack/bin/spack: Argument list too long\r\n```\r\n\r\nI tried in a new shell to test each command and also cleaned the python cache in case, but what I got was:\r\n```\r\n$ spack clean --python-cache\r\n==> Removing python cache files\r\n$ spack load python%clang; spack load py-cython; spack load py-setuptools; spack load py-matplotlib; spack load py-numpy; spack load py-sympy; spack load py-mpmath; spack load py-babel; spack load py-docutils; spack load py-packaging; spack load py-scipy; spack load py-mpi4py; spack load openpmd-api%clang; spack load py-notebook\r\nspack:137: argument list too long: spack\r\nspack:137: argument list too long: spack\r\n```\r\n\r\nI played with the order and number of packages loaded and saw that it seems independent of order (and which packages are involved).\r\nIf I try to load above 9 of those packages, I get the error.\r\nBelow is an example where I didn't get it:\r\n\r\n```\r\n$ spack clean --python-cache\r\n==> Removing python cache files\r\n$  spack load python%clang; spack load py-cython; spack load py-setuptools; spack load py-mpi4py; spack load openpmd-api%clang; spack load py-notebook\r\n$\r\n```\r\n\r\nHave you seen this issue before?\r\nDo you have any suggestion on how to fix it?\r\nI think the issue might be from bash and not spack. But I never got it before.\r\nI didn't change my bash configuration (which actually is zsh) nor anything in my macOS machine recently.\r\n\r\nThanks for all the help,\r\nDiana\r\n\r\n### Error Message\r\nIn the shell where I ran the script I get:\r\n```\r\n$spack --debug --stacktrace load\r\nspack --debug --stacktrace load\r\nlib/spack/spack/cmd/__init__.py:102 ==> [2020-04-23-11:02:58.266462, 1839] Imported load from built-in commands\r\nlib/spack/spack/cmd/__init__.py:102 ==> [2020-04-23-11:02:58.267243, 1839] Imported load from built-in commands\r\nlib/spack/spack/config.py:727 ==> [2020-04-23-11:02:58.268906, 1839] Reading config file /Users/LDianaAmorim/Documents/opt/spack/etc/spack/defaults/config.yaml\r\nlib/spack/spack/database.py:334 ==> [2020-04-23-11:02:58.280709, 1839] DATABASE LOCK TIMEOUT: 3s\r\nlib/spack/spack/database.py:338 ==> [2020-04-23-11:02:58.280883, 1839] PACKAGE LOCK TIMEOUT: No timeout\r\nlib/spack/llnl/util/lock.py:537 ==> [2020-04-23-11:02:58.281526, 1839] READ LOCK (database): /Users/LDianaAmorim/Documents/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquiring] \r\nlib/spack/llnl/util/lock.py:178 ==> [2020-04-23-11:02:58.281796, 1839] read locking [0:0]: timeout 3 sec\r\nlib/spack/llnl/util/lock.py:477 ==> [2020-04-23-11:02:58.281986, 1839] READ LOCK (database): /Users/LDianaAmorim/Documents/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquired at 11:02:58.281846] \r\nlib/spack/llnl/util/lock.py:537 ==> [2020-04-23-11:02:58.325002, 1839] READ LOCK (database): /Users/LDianaAmorim/Documents/opt/spack/opt/spack/.spack-db/lock[0:0] [Releasing] \r\nlib/spack/llnl/util/lock.py:477 ==> [2020-04-23-11:02:58.325239, 1839] READ LOCK (database): /Users/LDianaAmorim/Documents/opt/spack/opt/spack/.spack-db/lock[0:0] [Released at 11:02:58.325097] \r\n```\r\n\r\nWhen I tested just the load command in a separate shell I get:\r\n```console\r\n$ spack --debug --stacktrace load\r\nspack:137: argument list too long: spack\r\n```\r\n\r\n### Information on your system\r\n\r\n```\r\n$ spack debug report\r\n* **Spack:** 0.14.2-773-b874b3e1f\r\n* **Python:** 3.7.3\r\n* **Platform:** darwin-catalina-skylake\r\n```\r\n\r\n```\r\n$ cat ~/.spack/darwin/packages.yaml\r\npackages:\r\n  cmake:\r\n    buildable: False\r\n    paths:\r\n      cmake@3.17.0: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/cmake-3.17.0-6exaq5d4lp7sxf77nhk6kfkuajiy3qwm\r\n  all:\r\n    providers:\r\n      mpi: [mpich, openmpi]\r\n```\r\n\r\n```\r\n$ cat ~/.spack/darwin/compilers.yaml \r\ncompilers:\r\n- compiler:\r\n    spec: clang@11.0.3-apple\r\n    paths:\r\n      cc: /usr/bin/clang\r\n      cxx: /usr/bin/clang++\r\n      f77: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-th2gg6gtbyz5ipoh5joauzedtwau6goi/bin/gfortran\r\n      fc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-th2gg6gtbyz5ipoh5joauzedtwau6goi/bin/gfortran\r\n    flags: {}\r\n    operating_system: catalina\r\n    target: x86_64\r\n    modules: []\r\n    environment:\r\n      unset: []\r\n    extra_rpaths: []\r\n- compiler:\r\n    spec: gcc@9.3.0\r\n    paths:\r\n      cc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-th2gg6gtbyz5ipoh5joauzedtwau6goi/bin/gcc\r\n      cxx: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-th2gg6gtbyz5ipoh5joauzedtwau6goi/bin/g++\r\n      f77: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-th2gg6gtbyz5ipoh5joauzedtwau6goi/bin/gfortran\r\n      fc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-th2gg6gtbyz5ipoh5joauzedtwau6goi/bin/gfortran\r\n    flags: {}\r\n    operating_system: catalina\r\n    target: x86_64\r\n    modules: []\r\n    environment: {}\r\n    extra_rpaths: []\r\n```\r\n\r\n### Additional information\r\n- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform\r\n- [x] I have searched the issues of this repo and believe this is not a duplicate\r\n- [x] I have run the failing commands in debug mode and reported the output\r\n",
    "performed_via_github_app": null
}