{
    "url": "https://api.github.com/repos/spack/spack/issues/17968",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/17968/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/17968/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/17968/events",
    "html_url": "https://github.com/spack/spack/issues/17968",
    "id": 675948591,
    "node_id": "MDU6SXNzdWU2NzU5NDg1OTE=",
    "number": 17968,
    "title": "Installation issue: charliecloud 0.16 & 0.17",
    "user": {
        "login": "g-mathias",
        "id": 40861554,
        "node_id": "MDQ6VXNlcjQwODYxNTU0",
        "avatar_url": "https://avatars.githubusercontent.com/u/40861554?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/g-mathias",
        "html_url": "https://github.com/g-mathias",
        "followers_url": "https://api.github.com/users/g-mathias/followers",
        "following_url": "https://api.github.com/users/g-mathias/following{/other_user}",
        "gists_url": "https://api.github.com/users/g-mathias/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/g-mathias/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/g-mathias/subscriptions",
        "organizations_url": "https://api.github.com/users/g-mathias/orgs",
        "repos_url": "https://api.github.com/users/g-mathias/repos",
        "events_url": "https://api.github.com/users/g-mathias/events{/privacy}",
        "received_events_url": "https://api.github.com/users/g-mathias/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 446616547,
            "node_id": "MDU6TGFiZWw0NDY2MTY1NDc=",
            "url": "https://api.github.com/repos/spack/spack/labels/build-error",
            "name": "build-error",
            "color": "ff3300",
            "default": false,
            "description": null
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 5,
    "created_at": "2020-08-10T08:06:55Z",
    "updated_at": "2020-08-21T15:15:06Z",
    "closed_at": "2020-08-21T15:15:06Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "I find two minor issues installing the latest charliecloud versions\r\n\r\n1. Encoding problem\r\n\r\n```console\r\n$ spack install charliecloud\r\n==> charliecloud: Executing phase: 'configure'\r\n==> Error: Exception occurred in writer daemon!\r\nTraceback (most recent call last):\r\n  File \"/dss/dsshome1/07/lu64bag3/src/spack_fork/lib/spack/llnl/util/tty/log.py\", line 644, in _writer_daemon\r\n    line = _retry(in_pipe.readline)()\r\n  File \"/dss/dsshome1/07/lu64bag3/src/spack_fork/lib/spack/llnl/util/tty/log.py\", line 703, in wrapped\r\n    return function(*args, **kwargs)\r\n  File \"/usr/lib64/python3.6/encodings/ascii.py\", line 26, in decode\r\n    return codecs.ascii_decode(input, self.errors)[0]\r\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 721: ordinal not in range(128)\r\n==> Error: BrokenPipeError: [Errno 32] Broken pipe\r\n\r\n/dss/dsshome1/07/lu64bag3/src/spack_fork/lib/spack/spack/build_environment.py:862, in child_process:\r\n        859            tb_string = traceback.format_exc()\r\n        860\r\n        861            # build up some context from the offending package so we can\r\n  >>    862            # show that, too.\r\n        863            package_context = get_package_context(tb)\r\n        864\r\n        865            build_log = None\r\n```\r\n* **Spack:** 0.15.0-457-73486df9f\r\n* **Python:** 3.6.10\r\n* **Platform:** linux-sles15-haswell\r\n\r\nGoogle tells me e.g. https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal\r\n\r\n[spack-build-out-py@3.6.10.txt](https://github.com/spack/spack/files/5049572/spack-build-out-py%403.6.10.txt)\r\n[spack-build-env-py@3.6.10.txt](https://github.com/spack/spack/files/5049573/spack-build-env-py%403.6.10.txt)\r\n\r\n2. Problem 1 does not show up for python 3.7.8, but a second problem occurs\r\n\r\nThe soft link commands in the makefiles of the test subdir are missing the `-T` option. Seemingly, this causes trouble if the `/tmp/` dir has the sticky bit set. \r\n* **Spack:** 0.15.3\r\n* **Python:** 3.7.8\r\n* **Platform:** linux-sles15-haswell\r\n\r\n```console\r\n==> Installing charliecloud\r\n==> No binary for charliecloud found: installing from source\r\n==> charliecloud: Executing phase: 'autoreconf'\r\n==> charliecloud: Executing phase: 'configure'\r\n==> charliecloud: Executing phase: 'build'\r\n==> charliecloud: Executing phase: 'install'\r\n==> Error: ProcessError: Command exited with status 2:\r\n    'make' '-j24' 'install'\r\n\r\n1 warning found in build log:\r\n     52    checking for squashfuse... no\r\n     53    checking for tar... tar\r\n     54    checking if in chroot... no\r\n     55    checking if user+mount namespaces work... yes\r\n     56    checking for wget... wget\r\n     57    checking if wget version >= 1.11... ok (1.20.3)\r\n  >> 58    configure: WARNING: forcing --disable-man: no suitable sphinx-build\r\n     59    checking that generated files are newer than configure... done\r\n     60    configure: creating ./config.status\r\n     61    config.status: creating Makefile\r\n     62    config.status: creating bin/Makefile\r\n     63    config.status: creating doc/Makefile\r\n     64    config.status: creating examples/Makefile\r\n```\r\n\r\nThe relevant section in spack-build-out.txt is\r\n```\r\nMaking install in test\r\nmake[1]: Entering directory '/gpfs/scratch/pr28fa/lu64bag3/lu64bag3/x86_64/spack-stage-charliecloud-0.16-vwfj3nhb4cvcmjlxbaz2ly4nl4>\r\nln -fs /tmp fixtures/symlink-to-tmp\r\nln: failed to create symbolic link 'fixtures/symlink-to-tmp/tmp': Operation not permitted\r\nmake[1]: *** [Makefile:664: all-local] Error 1\r\nmake[1]: Leaving directory '/gpfs/scratch/pr28fa/lu64bag3/lu64bag3/x86_64/spack-stage-charliecloud-0.16-vwfj3nhb4cvcmjlxbaz2ly4nl4v>\r\nmake: *** [Makefile:389: install-recursive] Error 1\r\n\r\n> ll -d /tmp\r\ndrwxrwxrwt 19 root root 8192 Aug 10 10:05 /tmp\r\n```\r\n[spack-build-out.txt](https://github.com/spack/spack/files/5049619/spack-build-out.txt)\r\n[spack-build-env.txt](https://github.com/spack/spack/files/5049620/spack-build-env.txt)\r\n\r\nFor 0.16 I've created a patch\r\n\r\n```\r\n--- a/test/Makefile.in\t2020-08-09 12:17:29.474772000 +0200\r\n+++ b/test/Makefile.in\t2020-08-09 12:18:40.766768940 +0200\r\n@@ -661,12 +661,12 @@\r\n \r\n # See comment about symlinks in examples/Makefile.am.\r\n @ENABLE_TEST_TRUE@all-local:\r\n-@ENABLE_TEST_TRUE@\tln -fs /tmp fixtures/symlink-to-tmp\r\n+@ENABLE_TEST_TRUE@\tln -fTs /tmp fixtures/symlink-to-tmp\r\n @ENABLE_TEST_TRUE@clean-local:\r\n @ENABLE_TEST_TRUE@\trm -f fixtures/symlink-to-tmp\r\n @ENABLE_TEST_TRUE@install-data-hook:\r\n @ENABLE_TEST_TRUE@\tmkdir $(DESTDIR)$(testdir)/fixtures\r\n-@ENABLE_TEST_TRUE@\tln -fs /tmp $(DESTDIR)$(testdir)/fixtures/symlink-to-tmp\r\n+@ENABLE_TEST_TRUE@\tln -fTs /tmp $(DESTDIR)$(testdir)/fixtures/symlink-to-tmp\r\n @ENABLE_TEST_TRUE@uninstall-hook:\r\n @ENABLE_TEST_TRUE@\trm -f $(DESTDIR)$(testdir)/fixtures/symlink-to-tmp\r\n @ENABLE_TEST_TRUE@\trmdir $(DESTDIR)$(testdir)/fixtures || true\r\n\r\n```\r\nthat fixes the problem. However, the patch does not work for 0.17 #17855 out of the box, so one would probably need to fix the Makefile.am and run autotools again.\r\n\r\n\r\n<!-- Some packages have maintainers who have volunteered to debug build failures. Run `spack maintainers <name-of-the-package>\r\n` and @mention them here if they exist. -->\r\npinging maintainers: @j-ogas @reidpr \r\n### General information\r\n\r\n<!-- These boxes can be checked by replacing [ ] with [x] or by clicking them after submitting the issue. -->\r\n- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform\r\n- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers\r\n- [x] I have uploaded the build log and environment files\r\n- [x] I have searched the issues of this repo and believe this is not a duplicate\r\n",
    "performed_via_github_app": null
}