{
    "url": "https://api.github.com/repos/spack/spack/issues/2968",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/2968/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/2968/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/2968/events",
    "html_url": "https://github.com/spack/spack/pull/2968",
    "id": 204336644,
    "node_id": "MDExOlB1bGxSZXF1ZXN0MTAzOTYyNDk4",
    "number": 2968,
    "title": "Fixing problem calling a property in PythonPackage",
    "user": {
        "login": "JavierCVilla",
        "id": 4431174,
        "node_id": "MDQ6VXNlcjQ0MzExNzQ=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4431174?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/JavierCVilla",
        "html_url": "https://github.com/JavierCVilla",
        "followers_url": "https://api.github.com/users/JavierCVilla/followers",
        "following_url": "https://api.github.com/users/JavierCVilla/following{/other_user}",
        "gists_url": "https://api.github.com/users/JavierCVilla/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/JavierCVilla/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/JavierCVilla/subscriptions",
        "organizations_url": "https://api.github.com/users/JavierCVilla/orgs",
        "repos_url": "https://api.github.com/users/JavierCVilla/repos",
        "events_url": "https://api.github.com/users/JavierCVilla/events{/privacy}",
        "received_events_url": "https://api.github.com/users/JavierCVilla/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2017-01-31T15:48:10Z",
    "updated_at": "2017-01-31T16:04:09Z",
    "closed_at": "2017-01-31T15:58:01Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "pull_request": {
        "url": "https://api.github.com/repos/spack/spack/pulls/2968",
        "html_url": "https://github.com/spack/spack/pull/2968",
        "diff_url": "https://github.com/spack/spack/pull/2968.diff",
        "patch_url": "https://github.com/spack/spack/pull/2968.patch"
    },
    "body": "This PR fixes a typo *introduced* in #2859 when calling `self.build_directory` property in PythonPackage that produces this error:\r\n\r\n```\r\n...\r\n==> No patches needed for py-setuptools\r\n==> Building py-setuptools [PythonPackage]\r\n==> Executing phase : 'build'\r\n==> Error: TypeError: 'str' object is not callable\r\n/my/path/spack/lib/spack/spack/build_systems/python.py:115, in setup_py:\r\n     112      def setup_py(self, *args):\r\n     113          setup = self.setup_file()\r\n     114  \r\n  >> 115          with working_dir(self.build_directory()):\r\n     116              self.python(setup, '--no-user-cfg', *args)\r\n```\r\n\r\nI've only removed the parenthesis, probably forgotten during the change from method calls to properties. After a quick check seems to be the only one with this problem.",
    "performed_via_github_app": null
}