{
    "url": "https://api.github.com/repos/spack/spack/issues/33",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/33/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/33/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/33/events",
    "html_url": "https://github.com/spack/spack/issues/33",
    "id": 69879224,
    "node_id": "MDU6SXNzdWU2OTg3OTIyNA==",
    "number": 33,
    "title": "scipy fails to build on RHEL6",
    "user": {
        "login": "certik",
        "id": 20568,
        "node_id": "MDQ6VXNlcjIwNTY4",
        "avatar_url": "https://avatars.githubusercontent.com/u/20568?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/certik",
        "html_url": "https://github.com/certik",
        "followers_url": "https://api.github.com/users/certik/followers",
        "following_url": "https://api.github.com/users/certik/following{/other_user}",
        "gists_url": "https://api.github.com/users/certik/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/certik/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/certik/subscriptions",
        "organizations_url": "https://api.github.com/users/certik/orgs",
        "repos_url": "https://api.github.com/users/certik/repos",
        "events_url": "https://api.github.com/users/certik/events{/privacy}",
        "received_events_url": "https://api.github.com/users/certik/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": {
        "login": "lee218llnl",
        "id": 3641995,
        "node_id": "MDQ6VXNlcjM2NDE5OTU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3641995?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lee218llnl",
        "html_url": "https://github.com/lee218llnl",
        "followers_url": "https://api.github.com/users/lee218llnl/followers",
        "following_url": "https://api.github.com/users/lee218llnl/following{/other_user}",
        "gists_url": "https://api.github.com/users/lee218llnl/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lee218llnl/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lee218llnl/subscriptions",
        "organizations_url": "https://api.github.com/users/lee218llnl/orgs",
        "repos_url": "https://api.github.com/users/lee218llnl/repos",
        "events_url": "https://api.github.com/users/lee218llnl/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lee218llnl/received_events",
        "type": "User",
        "site_admin": false
    },
    "assignees": [
        {
            "login": "lee218llnl",
            "id": 3641995,
            "node_id": "MDQ6VXNlcjM2NDE5OTU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3641995?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lee218llnl",
            "html_url": "https://github.com/lee218llnl",
            "followers_url": "https://api.github.com/users/lee218llnl/followers",
            "following_url": "https://api.github.com/users/lee218llnl/following{/other_user}",
            "gists_url": "https://api.github.com/users/lee218llnl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lee218llnl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lee218llnl/subscriptions",
            "organizations_url": "https://api.github.com/users/lee218llnl/orgs",
            "repos_url": "https://api.github.com/users/lee218llnl/repos",
            "events_url": "https://api.github.com/users/lee218llnl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lee218llnl/received_events",
            "type": "User",
            "site_admin": false
        }
    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2015-04-21T15:40:52Z",
    "updated_at": "2015-08-27T09:12:47Z",
    "closed_at": "2015-08-27T09:12:47Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "```\n==> Trying to fetch from https://pypi.python.org/packages/source/s/scipy/scipy-0.15.0.tar.gz\n######################################################################## 100.0%\n==> Staging archive: /home/certik/repos/spack/var/spack/stage/py-scipy@0.15.0%gcc@4.9.2=unknown_arch-ad579252/scipy-0.15.0.tar.gz\n==> Created stage in /home/certik/repos/spack/var/spack/stage/py-scipy@0.15.0%gcc@4.9.2=unknown_arch-ad579252.\n==> No patches needed for py-scipy.\n==> Building py-scipy.\n/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'\n  warnings.warn(msg)\n/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'setup_requires'\n  warnings.warn(msg)\n/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'\n  warnings.warn(msg)\nlapack_opt_info:\nopenblas_lapack_info:\n  libraries openblas not found in ['/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']\n  NOT AVAILABLE\n\nlapack_mkl_info:\nmkl_info:\n  libraries mkl,vml,guide not found in ['/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']\n  NOT AVAILABLE\n\n  NOT AVAILABLE\n\natlas_threads_info:\nSetting PTATLAS=ATLAS\n  libraries ptf77blas,ptcblas,atlas not found in /home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib\n  libraries lapack_atlas not found in /home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib\n  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib64\n  libraries lapack_atlas not found in /usr/local/lib64\n  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib\n  libraries lapack_atlas not found in /usr/local/lib\n  libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/sse2\n  libraries lapack_atlas not found in /usr/lib64/sse2\n  libraries ptf77blas,ptcblas,atlas not found in /usr/lib64\n  libraries lapack_atlas not found in /usr/lib64\n  libraries ptf77blas,ptcblas,atlas not found in /usr/lib\n  libraries lapack_atlas not found in /usr/lib\n  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/\n  libraries lapack_atlas not found in /usr/lib/\nnumpy.distutils.system_info.atlas_threads_info\n  NOT AVAILABLE\n\natlas_info:\n  libraries f77blas,cblas,atlas not found in /home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib\n  libraries lapack_atlas not found in /home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib\n  libraries f77blas,cblas,atlas not found in /usr/local/lib64\n  libraries lapack_atlas not found in /usr/local/lib64\n  libraries f77blas,cblas,atlas not found in /usr/local/lib\n  libraries lapack_atlas not found in /usr/local/lib\n  libraries f77blas,cblas,atlas not found in /usr/lib64/sse2\n  libraries lapack_atlas not found in /usr/lib64/sse2\n  libraries f77blas,cblas,atlas not found in /usr/lib64\n  libraries lapack_atlas not found in /usr/lib64\n  libraries f77blas,cblas,atlas not found in /usr/lib\n  libraries lapack_atlas not found in /usr/lib\n  libraries f77blas,cblas,atlas not found in /usr/lib/\n  libraries lapack_atlas not found in /usr/lib/\nnumpy.distutils.system_info.atlas_info\n  NOT AVAILABLE\n\n/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/system_info.py:1432: UserWarning: \n    Atlas (http://math-atlas.sourceforge.net/) libraries not found.\n    Directories to search for the libraries can be specified in the\n    numpy/distutils/site.cfg file (section [atlas]) or by setting\n    the ATLAS environment variable.\n  warnings.warn(AtlasNotFoundError.__doc__)\nlapack_info:\n  libraries lapack not found in ['/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']\n  NOT AVAILABLE\n\n/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/system_info.py:1443: UserWarning: \n    Lapack (http://www.netlib.org/lapack/) libraries not found.\n    Directories to search for the libraries can be specified in the\n    numpy/distutils/site.cfg file (section [lapack]) or by setting\n    the LAPACK environment variable.\n  warnings.warn(LapackNotFoundError.__doc__)\nlapack_src_info:\n  NOT AVAILABLE\n\n/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/system_info.py:1446: UserWarning: \n    Lapack (http://www.netlib.org/lapack/) sources not found.\n    Directories to search for the sources can be specified in the\n    numpy/distutils/site.cfg file (section [lapack_src]) or by setting\n    the LAPACK_SRC environment variable.\n  warnings.warn(LapackSrcNotFoundError.__doc__)\n  NOT AVAILABLE\n\nRunning from scipy source directory.\nTraceback (most recent call last):\n  File \"setup.py\", line 249, in <module>\n    setup_package()\n  File \"setup.py\", line 246, in setup_package\n    setup(**metadata)\n  File \"/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/core.py\", line 135, in setup\n    config = configuration()\n  File \"setup.py\", line 173, in configuration\n    config.add_subpackage('scipy')\n  File \"/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py\", line 966, in add_subpackage\n    caller_level = 2)\n  File \"/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py\", line 935, in get_subpackage\n    caller_level = caller_level + 1)\n  File \"/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py\", line 872, in _get_configuration_from_setup_py\n    config = setup_module.configuration(*args)\n  File \"scipy/setup.py\", line 16, in configuration\n    config.add_subpackage('linalg')\n  File \"/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py\", line 966, in add_subpackage\n    caller_level = 2)\n  File \"/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py\", line 935, in get_subpackage\n    caller_level = caller_level + 1)\n  File \"/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py\", line 872, in _get_configuration_from_setup_py\n    config = setup_module.configuration(*args)\n  File \"scipy/linalg/setup.py\", line 18, in configuration\n    raise NotFoundError('no lapack/blas resources found')\nnumpy.distutils.system_info.NotFoundError: no lapack/blas resources found\n==> Error: command '/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/bin/python setup.py install --prefix=/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-scipy@0.15.0-ad579252' returned error code 1\n```\n",
    "performed_via_github_app": null
}