{
    "url": "https://api.github.com/repos/spack/spack/issues/5870",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/5870/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/5870/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/5870/events",
    "html_url": "https://github.com/spack/spack/issues/5870",
    "id": 267750676,
    "node_id": "MDU6SXNzdWUyNjc3NTA2NzY=",
    "number": 5870,
    "title": "Using lmod in some cases raises a strange error",
    "user": {
        "login": "krafczyk",
        "id": 6449564,
        "node_id": "MDQ6VXNlcjY0NDk1NjQ=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6449564?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/krafczyk",
        "html_url": "https://github.com/krafczyk",
        "followers_url": "https://api.github.com/users/krafczyk/followers",
        "following_url": "https://api.github.com/users/krafczyk/following{/other_user}",
        "gists_url": "https://api.github.com/users/krafczyk/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/krafczyk/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/krafczyk/subscriptions",
        "organizations_url": "https://api.github.com/users/krafczyk/orgs",
        "repos_url": "https://api.github.com/users/krafczyk/repos",
        "events_url": "https://api.github.com/users/krafczyk/events{/privacy}",
        "received_events_url": "https://api.github.com/users/krafczyk/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2017-10-23T17:24:25Z",
    "updated_at": "2017-10-23T21:07:16Z",
    "closed_at": "2017-10-23T21:07:16Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "I'm trying to use lmod to test new changes to `setup-env.sh`, and I'm getting this bizarre error message:\r\n\r\n```\r\nspack -d help\r\n==> Reading config file /home/matthew/Software/NCSA/Vertical/spack/spack-dev/etc/spack/defaults/modules.yaml\r\nTraceback (most recent call last):\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/config.py\", line 279, in _read_config_file\r\n    data = _mark_overrides(syaml.load(f))\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/util/spack_yaml.py\", line 213, in load\r\n    return yaml.load(*args, **kwargs)\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/external/yaml/lib3/yaml/__init__.py\", line 72, in load\r\n    return loader.get_single_data()\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/external/yaml/lib3/yaml/constructor.py\", line 37, in get_single_data\r\n    return self.construct_document(node)\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/external/yaml/lib3/yaml/constructor.py\", line 46, in construct_document\r\n    for dummy in generator:\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/util/spack_yaml.py\", line 102, in construct_yaml_map\r\n    value = self.construct_mapping(node)\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/util/spack_yaml.py\", line 142, in construct_mapping\r\n    \"found already in-use key (%s)\" % key, key_node.start_mark)\r\nyaml.constructor.ConstructorError: while constructing a mapping\r\n  in \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/etc/spack/defaults/modules.yaml\", line 17, column 3\r\nfound already in-use key (lmod)\r\n  in \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/etc/spack/defaults/modules.yaml\", line 49, column 3\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/bin/spack\", line 81, in <module>\r\n    sys.exit(spack.main.main())\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/main.py\", line 548, in main\r\n    return _main(command, parser, args, unknown)\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/main.py\", line 436, in _main\r\n    spack.hooks.pre_run()\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/hooks/__init__.py\", line 69, in __call__\r\n    for module in all_hook_modules():\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/llnl/util/lang.py\", line 182, in __call__\r\n    self.cache[args] = self.func(*args)\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/hooks/__init__.py\", line 57, in all_hook_modules\r\n    mod = imp.load_source(mod_name, path)\r\n  File \"/usr/lib/python3.6/imp.py\", line 172, in load_source\r\n    module = _load(spec)\r\n  File \"<frozen importlib._bootstrap>\", line 675, in _load\r\n  File \"<frozen importlib._bootstrap>\", line 655, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 205, in _call_with_frames_removed\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/hooks/module_file_generation.py\", line 25, in <module>\r\n    import spack.modules\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/modules/__init__.py\", line 32, in <module>\r\n    from .dotkit import DotkitModulefileWriter\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/modules/dotkit.py\", line 28, in <module>\r\n    from .common import BaseConfiguration, BaseFileLayout\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/modules/common.py\", line 71, in <module>\r\n    configuration = spack.config.get_config('modules')\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/config.py\", line 409, in get_config\r\n    data = scope.get_section(section)\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/config.py\", line 180, in get_section\r\n    data   = _read_config_file(path, schema)\r\n  File \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/config.py\", line 287, in _read_config_file\r\n    \"Error parsing yaml%s: %s\" % (str(e.context_mark), e.problem))\r\nspack.config.ConfigFileError: Error parsing yaml  in \"/home/matthew/Software/NCSA/Vertical/spack/spack-dev/etc/spack/defaults/modules.yaml\", line 17, column 3: found already in-use key (lmod)\r\n```\r\n\r\nIt happens even when using `spack help` (as evidenced by the command and error message above), and on loading `etc/spack/defaults/modules.yaml`.\r\n\r\nIt seems to be taking issue with my enabling of the `lmod` option, complaining that its already in use. This is strange because this is the only config file on my system attempting to define the `lmod` option.\r\n\r\nThe only thing I can think of is that this particular installation of spack used to be a `tcl` installation, i.e. I was using `environment-modules` and am now attempting to test `lmod`. Do I need to clear the cache in `~/.spack` or something?\r\n\r\nI'll update with what I learn as I try to fix this bug.",
    "performed_via_github_app": null
}