{
    "url": "https://api.github.com/repos/spack/spack/issues/8507",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/8507/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/8507/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/8507/events",
    "html_url": "https://github.com/spack/spack/issues/8507",
    "id": 333440135,
    "node_id": "MDU6SXNzdWUzMzM0NDAxMzU=",
    "number": 8507,
    "title": "spack test fails with pytest version error",
    "user": {
        "login": "twang15",
        "id": 16219606,
        "node_id": "MDQ6VXNlcjE2MjE5NjA2",
        "avatar_url": "https://avatars.githubusercontent.com/u/16219606?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/twang15",
        "html_url": "https://github.com/twang15",
        "followers_url": "https://api.github.com/users/twang15/followers",
        "following_url": "https://api.github.com/users/twang15/following{/other_user}",
        "gists_url": "https://api.github.com/users/twang15/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/twang15/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/twang15/subscriptions",
        "organizations_url": "https://api.github.com/users/twang15/orgs",
        "repos_url": "https://api.github.com/users/twang15/repos",
        "events_url": "https://api.github.com/users/twang15/events{/privacy}",
        "received_events_url": "https://api.github.com/users/twang15/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 456341797,
            "node_id": "MDU6TGFiZWw0NTYzNDE3OTc=",
            "url": "https://api.github.com/repos/spack/spack/labels/tests",
            "name": "tests",
            "color": "b60205",
            "default": false,
            "description": "General test capability(ies)"
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 14,
    "created_at": "2018-06-18T21:23:51Z",
    "updated_at": "2018-06-20T19:35:11Z",
    "closed_at": "2018-06-20T19:35:11Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "Summary\r\n\r\nFollowing spack contribution guide (http://spack.readthedocs.io/en/latest/contribution_guide.html) to run \"spack test\" for unit test on develop branch, \"spack test\"  fails with the following error message:\r\n\r\n### Expected Result\r\n\r\nUnit test is running...\r\n\r\n### Actual Result\r\n```\r\n==> Reading config file /usr/workspace/wsa/wang102/temp/spack/etc/spack/defaults/modules.yaml\r\n==> Reading config file /usr/workspace/wsa/wang102/temp/spack/etc/spack/defaults/config.yaml\r\nTraceback (most recent call last):\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/bin/spack\", line 85, in <module>\r\n    sys.exit(spack.main.main())\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/spack/main.py\", line 608, in main\r\n    return _main(command, parser, args, unknown)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/spack/main.py\", line 500, in _main\r\n    return _invoke_spack_command(command, parser, args, unknown_args)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/spack/main.py\", line 408, in _invoke_spack_command\r\n    return_val = command(parser, args, unknown_args)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/spack/cmd/test.py\", line 112, in test\r\n    return pytest.main(unknown_args + args.tests)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/config.py\", line 49, in main\r\n    config = _prepareconfig(args, plugins)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/config.py\", line 168, in _prepareconfig\r\n    pluginmanager=pluginmanager, args=args)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py\", line 745, in __call__\r\n    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py\", line 339, in _hookexec\r\n    return self._inner_hookexec(hook, methods, kwargs)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py\", line 334, in <lambda>\r\n    _MultiCall(methods, kwargs, hook.spec_opts).execute()\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py\", line 613, in execute\r\n    return _wrapped_call(hook_impl.function(*args), self.execute)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py\", line 250, in _wrapped_call\r\n    wrap_controller.send(call_outcome)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/helpconfig.py\", line 68, in pytest_cmdline_parse\r\n    config = outcome.get_result()\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py\", line 280, in get_result\r\n    _reraise(*ex)  # noqa\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py\", line 265, in __init__\r\n    self.result = func()\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py\", line 614, in execute\r\n    res = hook_impl.function(*args)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/config.py\", line 957, in pytest_cmdline_parse\r\n    self.parse(args)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/config.py\", line 1121, in parse\r\n    self._preparse(args, addopts=addopts)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/config.py\", line 1084, in _preparse\r\n    self.pluginmanager.load_setuptools_entrypoints('pytest11')\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py\", line 510, in load_setuptools_entrypoints\r\n    plugin = ep.load()\r\n  File \"/usr/tce/packages/python/python-2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 2302, in load\r\n    return self.resolve()\r\n  File \"/usr/tce/packages/python/python-2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 2308, in resolve\r\n    module = __import__(self.module_name, fromlist=['__name__'], level=0)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/assertion/rewrite.py\", line 212, in load_module\r\n    py.builtin.exec_(co, mod.__dict__)\r\n  File \"/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/py/_builtin.py\", line 221, in exec_\r\n    exec2(obj, globals, locals)\r\n  File \"<string>\", line 7, in exec2\r\n  File \"/usr/tce/packages/python/python-2.7.14/lib/python2.7/site-packages/hypothesis/extra/pytestplugin.py\", line 32, in <module>\r\n    re.sub('-.+', '', pytest.__version__).split('.')[:3]\r\nValueError: invalid literal for int() with base 10: 'unknown'\r\n```\r\n### Steps to reproduce the issue\r\n1. git clone https://github.com/spack/spack.git\r\n2. export $SPACK_ROOT=/path/to/spack/\r\n3. export PATH=$SPACK_ROOT/bin:$PATH\r\n4. source $SPACK_ROOT/share/spack/setup-env.sh\r\n5. follow contribution guide to install dependencies\r\n6. spack test\r\n\r\n### Information on your system\r\nspack: 0.11.2, development branch\r\nmachine architecture: Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz\r\nOS: (Red Hat Enterprise Linux Server release 7.4 (Maipo)\r\ncompiler: Intel 18.0.2",
    "performed_via_github_app": null
}